### ISSUE TITLE
any progress made so far?

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [Gocnak/sdk-2013-hammer#66]
this will be  a little unrelated but:
just wondering how much progress has you made?

**Comment by Gocnak** [comment]
You can check out the [projects page](https://github.com/Gocnak/sdk-2013-hammer/projects/1) for issues/things that have been fixed/implemented.
#9 is kinda coming along but I sorta despise MFC, so some areas aren't properly darkened.
Currently waiting on SCell's PR over at #23 to be merged in, has a lot in it.
Main focus of my coding efforts have been in Momentum's website and game. This project will pick up once that stabilizes.
