### ISSUE TITLE
Hammer not opening

### ISSUE THREAD

**Issue by gabriel0404** [Gocnak/sdk-2013-hammer#91]
I compiled hammer_dll.dll and hammer.exe with Visual Studio 2017 , then I moved those 2 files in 
`"C:\Program Files (x86)\Steam\steamapps\common\Source SDK Base 2013 Multiplayer\bin"`
when I try to open hammer nothing happens.

**Comment by Gocnak** [comment]
Have you read the README?

**Comment by gabriel0404** [comment]
Sorry , after reading the README more carefully I realized that I placed the files in the wrong directory
